#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    sum1,sum2,sum3=0,0,0
    for i in range(len(arr)):
        if arr[i]>0:
            sum1=sum1+1
        elif arr[i]<0:
            sum2=sum2+1
        else:
            sum3=sum3+1
    l1=sum1/len(arr)
    l2=sum2/len(arr)
    l3=sum3/len(arr)
    print(round(l1,6))
    print(round(l2,6))
    print(round(l3,6))

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
